### PR TITLE
intake modulizing

### LINKED ISSUE #136: Clean up intake

### PR DESCRIPTION
**Pull request by seankid**
uhh not sure why there was 512 commits

### CODE REVIEW

**Comment by owen-beck** [comment]
Revert the changes to Autonomous.java and RobotContainer.java, we will fix the errors later. Fix the merge conflicts in IntakeCommand.java.

**Comment by seankid** [comment]
so it says its fine but not sure if i did this correctly

**Comment by seankid** [comment]
i changed a lot of files so that they would let the robot code build correctly

**Review by renatodellosso — APPROVED** [review]
Looks good.

**Pull request merged**
